core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path(
        'playlistpost/list/',
        views.PlaylistPreviewView.as_view(),
        name='playlist_list'),
    path(
        'playlistpost/<slug:slug>/',
        views.PlaylistPostDetailView.as_view(),
        name='playlist_post_detail'),
    path(
        'playlistpost/<slug:slug>/edit_comment/<int:comment_id>',
        views.comment_edit, name='comment_edit'),
    path(
        'playlistpost/<slug:slug>/delete_comment/<int:comment_id>',
        views.comment_delete, name='comment_delete'),
    path(
        'playlistpost/<slug:slug>/likes', views.like_view, name='like_view'),
    path(
        'playlistpost/<slug:slug>/comment/<int:comment_id>/like/',
        views.like_comment,
        name='like_comment'
    ),
    path(
        'presentation/<str:username>/',
        views.user_profile_presentation,
        name='user_profile_presentation'),
]

core/models.py
from django.db import models
from django.core.validators import MaxLengthValidator
from django.contrib.auth.models import User
from user_profile.models import Playlist


class PlaylistPost(models.Model):
    """
    Stores user playlist publication instances
    """

    playlist = models.OneToOneField(
        Playlist, on_delete=models.CASCADE, related_name="playlist_post"
    )
    slug = models.SlugField(unique=True, null=False)
    likes = models.ManyToManyField(
        User, related_name="playlist_likes", blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def total_likes(self):
        return self.likes.count()

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.playlist.title} | by {self.playlist.author.username}"


class Comment(models.Model):
    """
    Stores a single comment entry related to User and to PlaylistPost.
    """
    playlist_post = models.ForeignKey(PlaylistPost, on_delete=models.CASCADE,
                                      related_name="comments")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter")
    content = models.TextField(
        # Limit characters to 500 as max_length does not apply to TextField
        validators=[MaxLengthValidator(500)])
    likes_comment = models.ManyToManyField(
        User, related_name="playlist_comments", blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def total_likes_comment(self):
        return self.likes_comment.count()

    # Check if the current user has liked the comment (False or True)
    # GETTER method decorator and definition:
    @property
    def is_liked_by_user(self):
        return self._is_liked_by_user

    # SETTER method decorator and definition:
    @is_liked_by_user.setter
    def is_liked_by_user(self, user):
        # prefix '_' to indicate that this is a private attribute
        self._is_liked_by_user = self.likes_comment.filter(id=user.id).exists()

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"Comment {self.content} by {self.author}"

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from cloudinary.models import CloudinaryField
from django.utils.text import slugify
from django.core.validators import MaxLengthValidator


class UserProfile(models.Model):
    """
    User Profile model that extends built-in User to add
    about_myself, avatar and date of birth fields: one-to-one
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
    )
    about_myself = models.TextField(
        _("about myself"),
        blank=True,
        # Limit characters to 500 as max_length does not apply to TextField
        validators=[MaxLengthValidator(1000)]
    )

    # Store avatars in the update UserAdmin model Cloudinary cloud
    avatar = CloudinaryField(
        'image',
        default='default_avatar',
        folder='slipknot-fan-avatars',
        blank=True
    )
    date_of_birth = models.DateField(_("date of birth"), null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} ({self.user.email})"


STATUS = ((0, "Draft"), (1, "Published"))
TYPE = ((0, "Original"), (1, "Cover"), (2, "Tutorial"), (3, "Inspired"))


class Playlist(models.Model):
    """
    Stores user playlist general info and umbrella image
    """
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="playlists"
    )
    featured_image = CloudinaryField(
        'image',
        folder='fanhub/playlist_images',
        blank=True)
    description = models.TextField(
        blank=True,
        # Limit characters to 1000 as max_length does not apply to TextField
        validators=[MaxLengthValidator(1000)])
    reference_url = models.URLField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]

    def is_author(self, user):
        return self.author == user

    def save(self, *args, **kwargs):
        if self.pk:  # Check if the instance already exists
            original = Playlist.objects.get(pk=self.pk)
            if original.title != self.title:  # Check if the title has changed
                self.slug = slugify(self.title)
                # Ensure the slug is unique
                original_slug = self.slug
                num = 1
                while Playlist.objects.filter(slug=self.slug).exists():
                    self.slug = f'{original_slug}-{num}'
                    num += 1
        else:
            self.slug = slugify(self.title)
            # Ensure the slug is unique
            original_slug = self.slug
            num = 1
            while Playlist.objects.filter(slug=self.slug).exists():
                self.slug = f'{original_slug}-{num}'
                num += 1

        super(Playlist, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.title} | status: {self.get_status_display()}"


class PlaylistItem(models.Model):
    """
    Stores playlist items
    """
    playlist = models.ForeignKey(
        Playlist, on_delete=models.CASCADE, related_name="playlist_items"
    )
    song_title = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    album = models.CharField(max_length=200, blank=True)
    song_url = models.URLField(blank=True)
    song_audio = CloudinaryField(
        'audios',
        resource_type='raw',
        folder='fanhub/song_audios',
        blank=True,
    )
    song_tabs = CloudinaryField(
        'docs',
        resource_type='raw',
        folder='fanhub/song_tabs',
        blank=True,
    )
    song_comments = models.TextField(
        blank=True,
        # Limit characters to 500 as max_length does not apply to TextField
        validators=[MaxLengthValidator(800)])
    performance_year = models.IntegerField(
        verbose_name="Year of Performance", blank=True, null=True)
    performance_type = models.IntegerField(choices=TYPE, default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (
            f"'{self.song_title}' by {self.artist} | "
        )

core/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    """
    ModelForm class for users to create comment on a playlist_post
    """
    class Meta:
        """
        Specify the django model and order of the fields
        """
        model = Comment
        fields = ('content',)

core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import PlaylistPost, Comment
from user_profile.models import Playlist, UserProfile, PlaylistItem
from .forms import CommentForm


# Apart from general context creates dynamic blog post context with pagination
def home_view(request):
    # Annotating each PlaylistPost with the count of related comments
    playlist_posts = PlaylistPost.objects.annotate(
        comment_count=Count('comments')).order_by('-created_on')

    playlists = Playlist.objects.filter(playlist_post__isnull=False)

    # Pagination logic
    paginator = Paginator(playlist_posts, 5)  # Show 5 posts per page
    page = request.GET.get('page')

    try:
        paginated_posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        paginated_posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        paginated_posts = paginator.page(paginator.num_pages)

    context = {
        'playlist_posts': paginated_posts,
        'playlists': playlists,
    }
    return render(request, 'core/home.html', context)


class PlaylistPreviewView(TemplateView):
    """
    Creating context and view for the full list of shared playlists page.
    """

    template_name = 'core/playlist_preview.html'
    context_object_name = 'playlist_posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Fetching all PlaylistPost objects ordered by '-created_on'
        # and select related Playlist objects
        playlist_posts = PlaylistPost.objects.select_related(
            'playlist').order_by('-created_on')

        # Adding PlaylistPost objects to the context
        context['playlist_posts'] = playlist_posts

        return context


# Creating context for author presentation page with info and playlists
def user_profile_presentation(request, username):
    user_profile = get_object_or_404(
        UserProfile.objects.select_related('user'), user__username=username)
    profile_user = user_profile.user
    playlists = Playlist.objects.filter(author=profile_user, status=1)

    # Create a list comprehension to hold playlists with their associated
    # PlaylistPost slugs. The goal is to avoid creation of extra views and
    # templates and enable user to access the existing PlaylistPost detail view
    playlist_with_posts = [
        {
            'playlist': playlist,
            'playlist_post_slug': (
                PlaylistPost.objects.get(playlist=playlist).slug)
        }
        for playlist in playlists
    ]

    return render(
        request,
        'core/user_profile_presentation.html',
        {'profile_user': profile_user,
         'user_profile': user_profile,
         'playlist_with_posts': playlist_with_posts}
    )


class PlaylistPostDetailView(DetailView):
    """
    Display a Playlist Detail view selected on the home page.
    Creating contexts: playlists, playlist items, author's profile,
    comments, comment count and comment form
    """

    model = PlaylistPost
    template_name = 'core/playlist_post_detail.html'
    context_object_name = 'playlist_post'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        playlist = self.object.playlist
        user = self.request.user

        # Adding playlist, author profile, and playlist items to context
        context['playlist'] = playlist
        context['author_profile'] = UserProfile.objects.get(
            user=playlist.author)
        context['playlist_items'] = PlaylistItem.objects.filter(
            playlist=playlist)

        # Adding comments and comment form to context
        comments = self.object.comments.all()

        # Check if the current user has liked the comment (False or True)
        for comment in comments:
            comment.is_liked_by_user = user

        comment_count = comments.count()
        comment_form = CommentForm()

        context['comments'] = comments
        context['comment_count'] = comment_count
        context['comment_form'] = comment_form

        # Check if the current user has liked the playlist_post (False or True)
        context['liked'] = self.object.likes.filter(id=user.id).exists()

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.playlist_post = self.object
            new_comment.author = request.user
            new_comment.save()
            return redirect('playlist_post_detail', slug=self.object.slug)
        else:
            context = self.get_context_data()
            context['comment_form'] = comment_form
            return self.render_to_response(context)


def comment_edit(request, slug, comment_id):
    """
    Display an individual comment for edit.
    Template is equipped with JavaScript to populate comment form with content.
    """

    post = get_object_or_404(PlaylistPost, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error updating comment!')

    return HttpResponseRedirect(reverse('playlist_post_detail', args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    view to delete comments and redirect to the PlaylistPost detail page.
    """

    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('playlist_post_detail', args=[slug]))


@login_required
def like_view(request, slug):
    post = get_object_or_404(PlaylistPost, slug=slug)

    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    return HttpResponseRedirect(reverse('playlist_post_detail', args=[slug]))


@login_required
def like_comment(request, slug, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if comment.likes_comment.filter(id=request.user.id).exists():
        comment.likes_comment.remove(request.user)
    else:
        comment.likes_comment.add(request.user)

    return redirect(reverse('playlist_post_detail', args=[slug]))

core/templates/core/navbar-signed.html
<p id="hello-user">Hello, <span class="username">{{ request.user.username }}!</span></p>
<nav class="nav">
    <input type="checkbox" id="menuToggle" class="menu-toggle hidden">
    <label for="menuToggle" class="menu-icon color-white">&#9776;</label>
    <div class="navbar">
        <div class="header-menu">
            <a href="{% url 'home' %}" class="nav-item nav-link" aria-label="back to the home page">Home</a>
            <a href="{% url 'profile' %}" class="nav-item nav-link" aria-label="go to your profile">Your Profile</a>
            <a href="{% url 'account_logout' %}" class="nav-item nav-link" aria-label="sign out">Sign Out</a>
        </div>
    </div>
</nav>

core/templates/core/navbar-signup.html
<nav class="nav">
    <input type="checkbox" id="menuToggle" class="menu-toggle hidden">
    <label for="menuToggle" class="menu-icon">&#9776;</label>
    <div class="navbar">
        <div class="header-menu">
            <a href="{% url 'home' %}" class="nav-item nav-link" aria-label="back to the home page">Home</a>
            <a href="{% url 'account_signup' %}" class="nav-item nav-link" aria-label="sign up">Sign Up</a>
            <a href="{% url 'account_login' %}" class="nav-item nav-link" aria-label="login">Login</a>
        </div>
    </div>
</nav>

core/templates/core/playlist_post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}

{% block title %}Playlist presentation{% endblock %}
{% block extra_head %}
<!-- Custom CSS for core application playlist_post_detail.html -->
<link rel="stylesheet" href="{% static 'core/css/core_styles.css' %}" />
{% endblock extra_head %}

{% block main_content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
</ul>
{% endif %}
<div class="grid-post-detail flex-evenly container flex-1-1">

    <section class="playlist-description flex-column-left">
        <h2>Playlist Details:</h2>
        <h3>"{{ playlist_post.playlist.title }}" shared by &nbsp; &nbsp;
            <span>
                {% if "default_avatar" in author_profile.avatar.url %}
                <a href="{% url 'user_profile_presentation'  author_profile.user.username %}"
                    aria-label="link to the {{ author_profile.user.username }}'s page" id="playlist-author-avatar">
                    <img src="{% static 'images/nobody.jpg' %}" alt="default avatar">
                </a>
                {% else %}
                <a href="{% url 'user_profile_presentation'  author_profile.user.username %}"
                    aria-label="link to the {{ author_profile.user.username }}'s page" id="playlist-author-avatar">
                    <img src="{{ author_profile.avatar.url }}" alt="{{ author_profile.user.username }}'s avatar">
                </a>
                {% endif %}
            </span>
            <span id="palylist-author-name">
                <a href="{% url 'user_profile_presentation'  author_profile.user.username %}"
                    aria-label="link to the {{ author_profile.user.username }}'s page">{{ author_profile.user.username }}</a>
            </span>
        </h3>
        <article class="flex-column-left">
            <h3 class="hidden">Playlist presentation</h3>
            {% if playlist_post.playlist.featured_image %}
            <div class="featured-image">
                <img src="{{ playlist_post.playlist.featured_image.url }}" alt="'{{playlist_post.playlist.title }}' featured image">
            </div>
            {% else %}
            <p>No Featured image provided by Author</p>
            {% endif %}
            <div class="playlist-description">
                <p>Description:</p>
                <div class="text-description shadow-white padding-20">
                    {{ playlist_post.playlist.description | linebreaks }}</div>
            </div>
            {% if playlist_post.playlist.reference_url %}
            <a href="{{ playlist_post.playlist.reference_url }}"
                aria-label="url reference featuring playlist main message" target="_blank">🔗 The Author has provided
                this link for your reference (opens in a new window)</a>
            {% endif %}
            <p>Created on: {{ playlist_post.created_on }}</p>

            <p>Total Comments: {{ comment_count }}</p>
        </article>

        <div class="flex-start">
            <form action="{% url 'like_view' playlist_post.slug %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="likes 
                {% if liked %}
                back-red
                {% else %}
                back-transparent
                {% endif %}">&#129311;&#127995;</button>
            </form>
            <p>{{ playlist_post.total_likes }} likes</p>
        </div>
    </section>

    <section class="playlist-items-container box-shadow back-dark padding-20">
        <h2>Songs or other Items in this Playlist:</h2>
        <ul class="flex-column-left">
            {% for item in playlist_items %}
            <li>
                {{ item }} {{ item.get_performance_type_display }}
                <input type="checkbox" id="nav-toggle-{{ forloop.counter }}" class="nav-toggle hidden"
                    name="nav-toggle">
                <label for="nav-toggle-{{ forloop.counter }}" class="nav-toggle--label"><i
                        class="fa-solid fa-bars"></i></label>
                <article class="playlist-item pop-down flex-column-left">
                    <h3 class="hidden">Song/Item presentation</h3>
                    <div>
                        <p class="playlist-item--field-title">Artist/Author:</p>
                        <p>{{ item.artist }}</p>
                    </div>
                    <div>
                        {% if item.album %}
                        <p class="playlist-item--field-title">Album:</p>
                        <p>{{ item.album }}</p>
                        {% endif %}
                    </div>
                    <div>
                        {% if item.song_url %}
                        <a href="{{ item.song_url }}" aria-label="link reference to the song" target="_blank">🔗 Reference
                            link provided by {{ playlist_post.playlist.author }}</a>
                        {% endif %}
                    </div>
                    <div>
                        {% if item.song_audio %}
                        <p class="playlist-item--field-title">Song Audio:</p>
                        <audio id="audio-example" controls>
                            <source src="{{ item.song_audio.url }}" type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>
                        {% endif %}
                    </div>
                    <div>
                        {% if item.song_tabs %}
                        <p class="playlist-item--field-title">Song Docs (song tabs, lyrics or other useful stuff):</p>
                        <a href="{{ item.song_tabs.url }}" download target="_blank" rel="noopener noreferrer"
                            aria-label="link to the song docs file">🔗 Preview doc file here and download if you
                            need</a>
                        {% endif %}
                    </div>
                    <div>
                        {% if item.performance_year %}
                        <p class="playlist-item--field-title">Performed in:</p>
                        <p>{{ item.performance_year }}</p>
                        {% endif %}
                    </div>
                    <div>
                        <p class="playlist-item--field-title">The song category:</p>
                        <p>{{ item.get_performance_type_display }}</p>
                    </div>
                    <div>
                        {% if item.song_comments %}
                        <p class="playlist-item--field-title">The Playlist's Author comments on the song:</p>
                        {{ item.song_comments | linebreaks }}
                        {% endif %}
                    </div>
                </article>
            </li>

            {% endfor %}
        </ul>
    </section>

</div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
</ul>
{% endif %}

<section class="playlist-comment container">
    <h2>Comments:</h2>
    <div class="flex-evenly">
        <div class="flex-column-left">
            {% for comment in comments %}
            <div>
                <p class="label-for-comments"><strong>{{ comment.author }}</strong> made a comment {{ comment.created_on|timesince }} ago:</p>
                <div class="flex-start-end">
                    <div id="comment{{ comment.id }}" class="comment-content shadow-white">
                        {{ comment.content | linebreaks }}
                    </div>
                    {% if user.is_authenticated and comment.author == user %}
                    <button class="btn-edit btn-form" data-comment_id="{{ comment.id }}">Edit</button>
                    <button class="btn-delete btn-form back-red color-white"
                        data-comment_id="{{ comment.id }}">Delete</button>
                    {% endif %}
                </div>
                <div class="flex-start">
                    <form action="{% url 'like_comment' playlist_post.slug comment.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="likes-comment 
                        {% if comment.is_liked_by_user %}
                        back-red
                        {% else %}
                        back-transparent
                        {% endif %}">&#129311;&#127995;</button>
                    </form>
                    <p>{{ comment.total_likes_comment }} likes</p>
                </div>
            </div>
            {% empty %}
            <p>No comments yet. Be the first to comment!</p>
            {% endfor %}
        </div>

        {% if user.is_authenticated %}
        <div class="comment-form-container box-shadow back-dark padding-20 flex-column-left">
            <div>
                <h3 id="formTitle">Add a Comment</h3>
                <p><small>(drag bottom-right corner of the window to resize)</small></p>
            </div>
            <form id="commentForm" method="post" class="add-comment-form">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <button id="submitButton" type="submit" class="btn-form">
                    Submit
                </button>
            </form>
            <a href="{% url 'playlist_post_detail' playlist_post.slug %}" id="discardChanges" class="hidden">Discard
                Changes</a>
        </div>
        {% else %}
        <p>Log in to leave a comment</p>
        {% endif %}
    </div>
</section>

<div id="modalCommentDelete" class="modal">
    <div class="modal-content">
        <p class="close">&times;</p>
        <h2>Are you sure you want to delete this comment?</h2>
        <a href="#" id="deleteConfirm" class="back-red color-white" aria-label="confirm delete">Confirm Delete</a>
    </div>
</div>

{% endblock main_content %}

{% block bottom %}
<script src="{% static 'js/item-detail-toggle.js' %}"></script>
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}

core/templates/core/playlistpost_detail.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'core/css/core_styles.css' %}" />
{% endblock extra_head %}

{% block main_content %}


<div class="grid-post-detail grid">

    <section class="playlist-description">
        <h2>"{{ playlistpost.playlist.title }}" shared by &nbsp; &nbsp;
            <span>
                {% if author_profile.avatar.url %}
                <a href="#" aria-label="link to the author profile page" id="playlist-author-avatar">
                    {% cloudinary author_profile.avatar %}</a>
                {% endif %}
            </span>
            <span id="palylist-author-name">
                <a href="#" aria-label="link to the author profile page">{{ author_profile.user.username }}</a>
            </span>
        </h2>
    
        <article>
            {% if playlistpost.playlist.featured_image %}
            <div class="featured-image">
                {% cloudinary playlistpost.playlist.featured_image %}
            </div>
            {% else %}
            <p>No Featured image provided by Author</p>
            {% endif %}
    
            <p>{{ playlistpost.playlist.description | safe }}</p>
            {% if playlistpost.playlist.reference_url %}
            <a href="{{ playlistpost.playlist.reference_url }}" aria-label="url reference featuring playlist main message"
                target="_blank">The Author has provided this link for your reference (opens in a new window)</a>
            {% endif %}
            <p>Likes: {{ playlistpost.total_likes }}</p>
            <p>Created on: {{ playlistpost.created_on }}</p>
        </article>
    </section>
    <section class="playlist-items-container">
        <h2>Songs or other Items in this Playlist:</h2>
        <ul class="flex-column">
            {% for item in playlist_items %}
            <li>{{ item }} Performance Type: {{ item.get_performance_type_display }}</li>
            <article class="playlist-item pop-down">
                <div>
                    <p>Artist/Author:</p>
                    <p>{{ item.artist }}</p>
                </div>
                <div>
                    {% if item.album %}
                    <p>Album:</p>
                    <p>{{ item.album }}</p>
                    {% endif %}
                </div>
                <div>
                    {% if item.song_url %}
                    <a href="{{ item.song_url }}" aria-label="link reference to the song" target="_blank">Follow this
                        link provided by the Playlist's Author</a>
                    {% endif %}
                </div>
                <div>
                    {% if item.song_audio %}
                    <p>Song Audio:</p>
                    <a href="{{ item.song_audio.url }}" aria-label="link to the song audio file">Follow this link to
                        download audio file</a>
                    {% endif %}
                </div>
                <div>
                    {% if item.song_tabs %}
                    <p>Song Docs (song tabs/notation or other useful stuff):</p>
                    <a href="{{ item.song_tabs.url }}" aria-label="link to the song docs file">Follow this link</a>
                    {% endif %}
                </div>
                <div>
                    {% if item.performance_year %}
                    <p>Performed in:</p>
                    <p>{{ item.performance_year }}</p>
                    {% endif %}
                </div>
                <div>
                    <p>The song category:</p>
                    <p>{{ item.get_performance_type_display }}</p>
                </div>
                <div>
                    {% if item.song_comments %}
                    <p>The Playlist's Author comments on the song:</p>
                    <p>{{ item.song_comments | linebreaks }}</p>
                    {% endif %}
                </div>
            </article>
            {% endfor %}
        </ul>
    </section>
</div>

{% endblock main_content %}